const Themes = {
  definitions: {
    default: {
      name: "Default",
    },
    minimal_dark: {
      name: "Minimal Dark",
      vars: {
        "--vimium-background-color": "#1a1a2e",
        "--vimium-background-text-color": "#e0e0e0",
        "--vimium-foreground-color": "#16213e",
        "--vimium-foreground-text-color": "#e0e0e0",
        "--vimium-link-color": "#64b5f6",
        "--vimium-vomnibar-bg": "#1a1a2e",
        "--vimium-vomnibar-border": "none",
        "--vimium-vomnibar-shadow": "0 8px 32px rgba(0,0,0,0.6), 0 0 0 1px rgba(255,255,255,0.05)",
        "--vimium-vomnibar-border-radius": "12px",
        "--vimium-vomnibar-input-bg": "#16213e",
        "--vimium-vomnibar-input-color": "#e0e0e0",
        "--vimium-vomnibar-input-border": "1px solid #0f3460",
        "--vimium-vomnibar-input-shadow": "none",
        "--vimium-vomnibar-search-area-border": "1px solid #0f3460",
        "--vimium-vomnibar-selected-bg": "#0f3460",
        "--vimium-vomnibar-url-color": "#64b5f6",
        "--vimium-vomnibar-title-color": "#e0e0e0",
        "--vimium-vomnibar-source-color": "#7986cb",
        "--vimium-vomnibar-match-color": "#fff",
        "--vimium-vomnibar-title-match-color": "#fff",
        "--vimium-vomnibar-separator-color": "rgba(255,255,255,0.1)",
        "--vimium-vomnibar-selection-bg": "#e0e0e0",
        "--vimium-hint-bg": "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
        "--vimium-hint-border": "none",
        "--vimium-hint-color": "#fff",
        "--vimium-hint-match-color": "rgba(255,255,255,0.5)",
        "--vimium-hint-border-radius": "4px",
        "--vimium-hint-shadow": "0 2px 8px rgba(102,126,234,0.4)",
        "--vimium-hud-bg": "#1a1a2e",
        "--vimium-hud-color": "#e0e0e0",
        "--vimium-hud-border": "1px solid #0f3460",
        "--vimium-hud-shadow": "0 4px 16px rgba(0,0,0,0.4)",
        "--vimium-help-bg": "#1a1a2e",
        "--vimium-help-border": "1px solid #0f3460",
        "--vimium-help-text-color": "#e0e0e0",
        "--vimium-help-heading-color": "#fff",
        "--vimium-help-link-color": "#64b5f6",
        "--vimium-help-divider-color": "rgba(255,255,255,0.1)",
        "--vimium-help-description-color": "#b0b0b0",
      },
    },
    catppuccin: {
      name: "Catppuccin Mocha",
      vars: {
        "--vimium-background-color": "#1e1e2e",
        "--vimium-background-text-color": "#cdd6f4",
        "--vimium-foreground-color": "#313244",
        "--vimium-foreground-text-color": "#cdd6f4",
        "--vimium-link-color": "#89b4fa",
        "--vimium-vomnibar-bg": "#1e1e2e",
        "--vimium-vomnibar-border": "1px solid #313244",
        "--vimium-vomnibar-shadow": "0 8px 32px rgba(0,0,0,0.5)",
        "--vimium-vomnibar-border-radius": "12px",
        "--vimium-vomnibar-input-bg": "#313244",
        "--vimium-vomnibar-input-color": "#cdd6f4",
        "--vimium-vomnibar-input-border": "1px solid #45475a",
        "--vimium-vomnibar-input-shadow": "none",
        "--vimium-vomnibar-search-area-border": "1px solid #45475a",
        "--vimium-vomnibar-selected-bg": "#45475a",
        "--vimium-vomnibar-url-color": "#89b4fa",
        "--vimium-vomnibar-title-color": "#cdd6f4",
        "--vimium-vomnibar-source-color": "#a6adc8",
        "--vimium-vomnibar-match-color": "#f5c2e7",
        "--vimium-vomnibar-title-match-color": "#f5c2e7",
        "--vimium-vomnibar-separator-color": "rgba(255,255,255,0.1)",
        "--vimium-vomnibar-selection-bg": "#cdd6f4",
        "--vimium-hint-bg": "linear-gradient(135deg, #f38ba8 0%, #eba0ac 100%)",
        "--vimium-hint-border": "none",
        "--vimium-hint-color": "#1e1e2e",
        "--vimium-hint-match-color": "rgba(30,30,46,0.4)",
        "--vimium-hint-border-radius": "6px",
        "--vimium-hint-shadow": "0 2px 8px rgba(243,139,168,0.3)",
        "--vimium-hud-bg": "#1e1e2e",
        "--vimium-hud-color": "#cdd6f4",
        "--vimium-hud-border": "1px solid #313244",
        "--vimium-hud-shadow": "0 4px 12px rgba(0,0,0,0.3)",
        "--vimium-help-bg": "#1e1e2e",
        "--vimium-help-border": "1px solid #313244",
        "--vimium-help-text-color": "#cdd6f4",
        "--vimium-help-heading-color": "#cdd6f4",
        "--vimium-help-link-color": "#89b4fa",
        "--vimium-help-divider-color": "rgba(255,255,255,0.1)",
        "--vimium-help-description-color": "#a6adc8",
      },
    },
    nord: {
      name: "Nord",
      vars: {
        "--vimium-background-color": "#2e3440",
        "--vimium-background-text-color": "#eceff4",
        "--vimium-foreground-color": "#3b4252",
        "--vimium-foreground-text-color": "#eceff4",
        "--vimium-link-color": "#88c0d0",
        "--vimium-vomnibar-bg": "#2e3440",
        "--vimium-vomnibar-border": "1px solid #3b4252",
        "--vimium-vomnibar-shadow": "0 4px 24px rgba(0,0,0,0.4)",
        "--vimium-vomnibar-border-radius": "8px",
        "--vimium-vomnibar-input-bg": "#3b4252",
        "--vimium-vomnibar-input-color": "#eceff4",
        "--vimium-vomnibar-input-border": "1px solid #4c566a",
        "--vimium-vomnibar-input-shadow": "none",
        "--vimium-vomnibar-search-area-border": "1px solid #4c566a",
        "--vimium-vomnibar-selected-bg": "#434c5e",
        "--vimium-vomnibar-url-color": "#88c0d0",
        "--vimium-vomnibar-title-color": "#eceff4",
        "--vimium-vomnibar-source-color": "#81a1c1",
        "--vimium-vomnibar-match-color": "#ebcb8b",
        "--vimium-vomnibar-title-match-color": "#ebcb8b",
        "--vimium-vomnibar-separator-color": "rgba(255,255,255,0.1)",
        "--vimium-vomnibar-selection-bg": "#eceff4",
        "--vimium-hint-bg": "linear-gradient(135deg, #ebcb8b 0%, #d08770 100%)",
        "--vimium-hint-border": "none",
        "--vimium-hint-color": "#2e3440",
        "--vimium-hint-match-color": "rgba(46,52,64,0.4)",
        "--vimium-hint-border-radius": "4px",
        "--vimium-hint-shadow": "0 2px 6px rgba(208,135,112,0.4)",
        "--vimium-hud-bg": "#2e3440",
        "--vimium-hud-color": "#eceff4",
        "--vimium-hud-border": "1px solid #3b4252",
        "--vimium-hud-shadow": "0 2px 8px rgba(0,0,0,0.3)",
        "--vimium-help-bg": "#2e3440",
        "--vimium-help-border": "1px solid #3b4252",
        "--vimium-help-text-color": "#eceff4",
        "--vimium-help-heading-color": "#eceff4",
        "--vimium-help-link-color": "#88c0d0",
        "--vimium-help-divider-color": "rgba(255,255,255,0.1)",
        "--vimium-help-description-color": "#d8dee9",
      },
    },
    glassmorphism: {
      name: "Glass",
      vars: {
        "--vimium-background-color": "rgba(255,255,255,0.45)",
        "--vimium-background-text-color": "#222",
        "--vimium-foreground-color": "rgba(255,255,255,0.3)",
        "--vimium-foreground-text-color": "#222",
        "--vimium-link-color": "#0e7c6b",
        "--vimium-backdrop-filter": "blur(16px)",
        "--vimium-vomnibar-bg": "rgb(255 255 255 / 0.7)",
        "--vimium-vomnibar-border": "none",
        "--vimium-vomnibar-shadow": "0 0 10px rgba(0,0,0,0.25), inset 0 0 2px 0px white",
        "--vimium-vomnibar-border-radius": "16px",
        "--vimium-vomnibar-input-bg": "rgba(255,255,255,0.4)",
        "--vimium-vomnibar-input-color": "#222",
        "--vimium-vomnibar-input-border": "1px solid rgba(255,255,255,0.5)",
        "--vimium-vomnibar-input-border-radius": "10px",
        "--vimium-vomnibar-input-shadow": "none",
        "--vimium-vomnibar-input-focus-ring": "0 0 0 2px #222",
        "--vimium-vomnibar-search-area-border": "none",
        "--vimium-vomnibar-shortcut-bg": "rgba(0,0,0,0.08)",
        "--vimium-vomnibar-hover-bg": "rgba(0,0,0,0.1)",
        "--vimium-vomnibar-selected-bg": "rgba(255,255,255,0.35)",
        "--vimium-vomnibar-url-color": "#0e7c6b",
        "--vimium-vomnibar-title-color": "#222",
        "--vimium-vomnibar-source-color": "rgba(0,0,0,0.4)",
        "--vimium-vomnibar-match-color": "#000",
        "--vimium-vomnibar-title-match-color": "#000",
        "--vimium-vomnibar-separator-color": "rgba(0,0,0,0.08)",
        "--vimium-vomnibar-selection-bg": "rgba(14, 124, 107, 0.25)",
        "--vimium-hint-bg": "rgba(255,255,255,0.5)",
        "--vimium-hint-border": "1px solid rgba(255,255,255,0.6)",
        "--vimium-hint-color": "#222",
        "--vimium-hint-match-color": "rgba(0,0,0,0.4)",
        "--vimium-hint-border-radius": "8px",
        "--vimium-hint-shadow": "0 2px 8px rgba(0,0,0,0.1)",
        "--vimium-hud-bg": "rgba(255,255,255,0.45)",
        "--vimium-hud-color": "#222",
        "--vimium-hud-border": "1px solid rgba(255,255,255,0.5)",
        "--vimium-hud-shadow": "0 2px 8px rgba(0,0,0,0.1)",
        "--vimium-help-dialog-scrim": "transparent",
        "--vimium-help-bg": "rgb(255 255 255 / 0.7)",
        "--vimium-help-border": "none",
        "--vimium-help-border-radius": "16px",
        "--vimium-help-shadow": "0 0 10px rgba(0,0,0,0.25), inset 0 0 2px 0px white",
        "--vimium-help-search-bg": "rgba(255,255,255,0.4)",
        "--vimium-help-search-border-radius": "10px",
        "--vimium-help-search-focus-ring": "0 0 0 2px rgba(0,0,0,0.2)",
        "--vimium-help-text-color": "#222",
        "--vimium-help-heading-color": "#111",
        "--vimium-help-link-color": "#0e7c6b",
        "--vimium-help-divider-color": "rgba(0,0,0,0.08)",
        "--vimium-help-description-color": "rgba(0,0,0,0.5)",
      },
    },
    tokyo_night: {
      name: "Tokyo Night",
      vars: {
        "--vimium-background-color": "#1a1b26",
        "--vimium-background-text-color": "#c0caf5",
        "--vimium-foreground-color": "#24283b",
        "--vimium-foreground-text-color": "#c0caf5",
        "--vimium-link-color": "#7dcfff",
        "--vimium-vomnibar-bg": "#1a1b26",
        "--vimium-vomnibar-border": "1px solid #24283b",
        "--vimium-vomnibar-shadow": "0 8px 32px rgba(0,0,0,0.5)",
        "--vimium-vomnibar-border-radius": "10px",
        "--vimium-vomnibar-input-bg": "#24283b",
        "--vimium-vomnibar-input-color": "#c0caf5",
        "--vimium-vomnibar-input-border": "1px solid #3b4261",
        "--vimium-vomnibar-input-shadow": "none",
        "--vimium-vomnibar-search-area-border": "1px solid #3b4261",
        "--vimium-vomnibar-selected-bg": "#283457",
        "--vimium-vomnibar-url-color": "#7dcfff",
        "--vimium-vomnibar-title-color": "#c0caf5",
        "--vimium-vomnibar-source-color": "#565f89",
        "--vimium-vomnibar-match-color": "#bb9af7",
        "--vimium-vomnibar-title-match-color": "#bb9af7",
        "--vimium-vomnibar-separator-color": "rgba(255,255,255,0.1)",
        "--vimium-vomnibar-selection-bg": "#c0caf5",
        "--vimium-hint-bg": "linear-gradient(135deg, #7aa2f7 0%, #bb9af7 100%)",
        "--vimium-hint-border": "none",
        "--vimium-hint-color": "#1a1b26",
        "--vimium-hint-match-color": "rgba(26,27,38,0.4)",
        "--vimium-hint-border-radius": "5px",
        "--vimium-hint-shadow": "0 2px 10px rgba(122,162,247,0.4)",
        "--vimium-hud-bg": "#1a1b26",
        "--vimium-hud-color": "#c0caf5",
        "--vimium-hud-border": "1px solid #24283b",
        "--vimium-hud-shadow": "0 4px 12px rgba(0,0,0,0.4)",
        "--vimium-help-bg": "#1a1b26",
        "--vimium-help-border": "1px solid #24283b",
        "--vimium-help-text-color": "#c0caf5",
        "--vimium-help-heading-color": "#c0caf5",
        "--vimium-help-link-color": "#7dcfff",
        "--vimium-help-divider-color": "rgba(255,255,255,0.1)",
        "--vimium-help-description-color": "#565f89",
      },
    },
  },

  getThemeNames() {
    return Object.entries(this.definitions).map(([key, def]) => ({
      key,
      name: def.name,
    }));
  },

  generateCss(themeName) {
    const theme = this.definitions[themeName];
    if (!theme || !theme.vars) return "";
    const declarations = Object.entries(theme.vars)
      .map(([prop, value]) => `  ${prop}: ${value};`)
      .join("\n");
    return `:root {\n${declarations}\n}`;
  },
};

globalThis.Themes = Themes;
